### ISSUE TITLE
No shifting

### ISSUE THREAD

**Issue by felixdorner** [printloop/google-sheets-opensea#1]
Thanks a lot for your script! I'm not that keen with JS and wonder how I need to adjust the code to only have one column with the current date and floor price? This could be overwritten each time. Cheers, Felix

**Comment by printloop** [comment]
Hey @felixdorner did you figure this out? I think if you just change shouldAddColumn to always return false it should work ( have not tested).

```
function shouldAddColumn(date){
     return false;
}
```

**Comment by felixdorner** [comment]
Hey @printloop, that helps. My hack was just to delete the column... Thanks a lot.
