### ISSUE TITLE
Could this be expanded? 

### ISSUE THREAD

**Issue by tanvidamani** [printloop/google-sheets-opensea#3]
Currently this only pulls floor price, correct? 

Could this be expanded to pull the following information from opensea? as a line? maybe in the same row? 
So what I mean is could it pull the following info: 
1. Name of Collection 
2. Date of Collection Creation
3. Collection Creator
4. Creator Royalty
5. Floor Price
6. Volume Traded

**Comment by printloop** [comment]
@painfullystoic certainly could be expanded without too much difficulty for most of the info you mentioned. The OpenSea collection API has a lot of it already. I wont be expanding on this anymore but you're welcome to use the code and add whatever other info you like. Happy to help if you have any questions.
